echo "Dit werkt niet als script! kopieeren...";
nvm install 10;
npm install -g gulp@3.9.1;
npm install gulp-autoprefixer@5.0.0; 
npm install gulp-concat@2.6.1;
npm install gulp-jshint@2.1.0;
npm install gulp-plumber@1.2.0;
npm install gulp-sass@4.0.0;
npm install gulp-sourcemaps@2.4.1;
npm install gulp-uglify@3.0.0;
npm install jshint@2.9.5; 
cd ../agitatie-kind;
npm install gulp-autoprefixer@5.0.0; 
npm install gulp-concat@2.6.1;
npm install gulp-jshint@2.1.0;
npm install gulp-plumber@1.2.0;
npm install gulp-sass@4.0.0;
npm install gulp-sourcemaps@2.4.1;
npm install gulp-uglify@3.0.0;
npm install jshint@2.9.5; 